language: php
cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.yarn"
  - "./node_modules"
before_install:
- yarn
jobs:
  include:
  - stage: master-build
    before_install:
    - chmod +x ./bin/push.sh
    script:
    - "./bin/push.sh"
    if: branch = master

